# This is a basic workflow to help you get started with Actions

name: Version

# Controls when the workflow will run
on:
  push: 
  pull_request:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Version
        id: version
        # You may pin to the exact commit or the version.
        # uses: juliansangillo/tag-version@0ca10cb901a4e3273715c4443e5dec5ad8f40328
        uses: juliansangillo/tag-version@v1.5
        with:
          # The branch to use for stable releases in production. Default is master
          production-branch: main
          # The branch to use for test deployments. Default is test
          # test-branch: test# optional, default is test
          # The branch to use for dev deployments. Default is develop
          # dev-branch: develop# optional, default is develop
      - run: |
        echo ${{ steps.version.revision }} > version.txt
