# This is a basic workflow to help you get started with Actions

name: Install NSIS

# Controls when the workflow will run
on:
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
          
    runs-on: windows-latest

    steps:
    - name: Checkout  
      uses: actions/checkout@v2  
        
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install scons
        
        
    - name: Install NSIS
      run: |
        # sudo apt-get install nsis
        git clone https://github.com/kichik/nsis.git
        Invoke-WebRequest Invoke-WebRequest "https://downloads.sourceforge.net/project/gnuwin32/zlib/1.2.3/zlib-1.2.3-bin.zip?ts=gAAAAABhIk-iqRs1LF0bwcyKZjA2aI1bc92c9c0WnjOHc7RP-M42tXaD287f7u_NXLrYCLbeKUzgk17ZZnjbAnKs78fSaEU4sA%3D%3D&r=https%3A%2F%2Fsourceforge.net%2Fprojects%2Fgnuwin32%2Ffiles%2Fzlib%2F1.2.3%2Fzlib-1.2.3-bin.zip%2Fdownload%3Fuse_mirror%3Ddeac-fra%26download%3D" -o zlib123dll.zip -o zlib123dll.zip
        Expand-Archive -Path .\zlib123dll.zip -DestinationPath C:\Dev\zlib\
        cd nsis/
        dir C:\Dev\zlib
        $Env:ZLIB_W32="C:\Dev\zlib"
        scons PREFIX="C:\Program Files\NSIS" install        
        cd ../
